theme: user-guide
components:
  - $
  - nav
plugins:
  - $
  - script-style-optimizer
  - files-promoter
default-layout: article
^code-syntax-highlighter:
  embed-style: false
^tipue-search:
  page-content-node: //article
  search-page-layout: default
^files-promoter:
  folders:
    - _content
    - _legal
$toc:
  home-menu-title: Welcome
  title-attribute: caption
  title-case: true
$nav:
  upper-case: true
  title-attribute: caption
  menu:
    - '[User Guide](/){ |/standard-library/* }'
    - '[Library](/standard-library/)'
$legal:
  company: Xarial Pty Limited
  links:
    Terms Of Use: /terms-of-use/
    Privacy: /privacy-policy/
    Cookies: /cookies-policy/
$cookie-consent:
  enable: true
  message: This website uses cookies to ensure you get the best experience on our website. By using our website you agree on the following <a href="/cookies-policy/">Cookie Policy</a>, <a href="/privacy-policy/">Privacy Policy</a>, and <a href="/terms-of-use">Terms Of Use</a>
$google-analytics:
  traking-code: UA-160707877-4
$disqus:
  short-name: docify
$social-links:
  linkedin: https://www.linkedin.com/company/xarial
  youtube: https://www.youtube.com/c/xarial
  nuget: https://www.nuget.org/profiles/Xarial
  github: https://github.com/xarial
  rss: /feed.xml
  reddit: https://www.reddit.com/r/docify/
  email: info@xarial.com
^script-style-optimizer:
  minify-css: true
  minify-js: true
  assets-scope-paths:
    - /_assets/styles/*
    - /_assets/scripts/*
  delete-unused-css: true
  delete-unused-js: true
  bundles:
    /_assets/styles/main.min.css:
      - /_assets/styles/social-share.css
      - /_assets/styles/youtube.css
      - /_assets/styles/base.css
      - /_assets/styles/toc.css
      - /_assets/styles/theme.css
      - /_assets/styles/user-guide.css
      - /_assets/styles/social-links.css
      - /_assets/styles/site-header.css
      - /_assets/styles/nav.css
      - /_assets/styles/responsive-image.css
      - /_assets/styles/syntax-highlight.css
      - /_assets/styles/code-snippet.css
    /_assets/scripts/main.min.js:
      - /_assets/scripts/toc.js
      - /_assets/scripts/nav.js
      - /_assets/scripts/code-snippet.js

lang: en
ignore:
  - $
  - .git\*
  - .gitignore
  - _plugins\_src\*
  - _includes\bin\*
  - _includes\obj\*
  - _includes\*.csproj
